explicitly set entry point and die if empty version

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -70,7 +70,11 @@ jobs:
         run: |
           app_version_command="$(cat ./${{ matrix.app }}/_get_version.sh | grep -e '^#' -v)"
           echo Running version command: $app_version_command
-          app_version=$(docker run --rm ${{ vars.DOCKER_USERNAME }}/${{ matrix.app }}:dev sh -c "${app_version_command}")
+          app_version=$(docker run --entrypoint sh --rm ${{ vars.DOCKER_USERNAME }}/${{ matrix.app }}:dev -c "${app_version_command}")
+          if [ -z "${app_version}" ]; then
+            echo "Error, failed to get version from ${{ matrix.app}}"
+            exit 1
+          fi
           major_app_version=`echo ${app_version} | cut -d'.' -f1`
 
           decider_version="build-${{ env.repo_major_minor }}_${{ matrix.app }}-${app_version}"
